name: 'Huawei Cloud OBS Sync Action'
description: 'Sync files or folders to Huawei Cloud OBS using obsutils.'
author: 'Emeka Raphael'
branding:
  icon: 'refresh-ccw'
  color: 'red'

inputs:
  accessKey:
    description: 'Access Key ID for Huawei Cloud OBS'
    required: true
  secretKey:
    description: 'Secret Key for Huawei Cloud OBS'
    required: true
  region:
    description: 'Endpoint for Huawei Cloud OBS' 
    required: true
  obsBucket:
    description: 'OBS bucket path'  
    required: true
  localPath:
    description: 'Path to the local folder or file for synchronization'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACCESS_KEY: ${{ inputs.accessKey }}
    SECRET_KEY: ${{ inputs.secretKey }}
    REGION: ${{ inputs.region }}
    BUCKET_NAME: ${{ inputs.obsBucket }}
    LOCAL_PATH: ${{ inputs.localPath }}